services:
  nginx:
    container_name: my-app-nginx-dev
    image: nginx:alpine
    ports:
      - "${NGINX_PORT}:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - frontend
      - backend
    networks:
      - my-app-network
  backend:
    container_name: my-app-backend-dev
    build:
      context: ./backend
      dockerfile: dev.Dockerfile
    env_file:
      - .env
    volumes:
      - ./backend/src:/app/src
      - ./backend/test:/app/test
    restart: always
    networks:
      - my-app-network
  frontend:
    container_name: my-app-frontend-dev
    build:
      context: ./frontend
      dockerfile: dev.Dockerfile
    env_file:
      - .env
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/public:/app/public
    restart: always
    networks:
      - my-app-network

networks:
  my-app-network:
    driver: bridge