services:
  nginx:
    container_name: my-app-nginx-prod
    image: nginx:alpine
    ports:
      - "${NGINX_PORT}:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - frontend
      - backend
    networks:
      - my-app-network
  backend:
    container_name: my-app-backend-prod
    build:
      context: backend
      dockerfile: prod.Dockerfile
    env_file:
      - .env
    restart: always
    networks:
      - my-app-network
  frontend:
    container_name: my-app-frontend-prod
    build:
      context: frontend
      dockerfile: prod.Dockerfile
    restart: always
    networks:
      - my-app-network

networks:
  my-app-network:
